Add context to the Insights Page #1012
open-sauced/insights pull request #1017
Opened 2023-03-15 22:45 UTC by nworiekingslee

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-03-15 23:00 UTC, bdougie commented
@nworiekingslee, please review the contributing guide. We need context when the PR is opened. This also include visual changes, screenshots are needed. 

Also confused, the copy is no where close to what I provided in the issue #1012.

2023-03-15 23:01 UTC, bdougie commented on pages/[filterName]/insights/index.tsx
> +            An insight page is a dashboard containing selected repositories that you and your team can get insights from.
```suggestion
            Welcome to your Insights Hub! Here, you can set up pages to view all of your insights or other open source insights in one place.
```

2023-03-15 23:07 UTC, bdougie requested changes
This works. Probably something like `sm:flex-col` but you'll have to look up if that is correct. 

Button should be on its own line. 

<img width="406" alt="Screen Shot 2023-03-15 at 4 15 18 PM" src="https://user-images.githubusercontent.com/5713670/225464863-f164b2c2-01c0-40b5-a2c7-897ca1a589b7.png">

2023-03-16 09:04 UTC, nworiekingslee commented
> @nworiekingslee, please review the contributing guide. We need context when the PR is opened. This also include visual changes, screenshots are needed.
> 
> Also confused, the copy is no where close to what I provided in the issue #1012.
> 
> update: I pushed a fix. Please update the PR description.

My bad.

2023-03-16 09:14 UTC, nworiekingslee commented on pages/[filterName]/insights/index.tsx
> -    getUser().catch(console.error).then(() => {});
Okay, I can help with this but it's not in the scope of the issue I am working on. Do you still need me to proceed?

2023-03-16 09:25 UTC, nworiekingslee commented
@bdougie I have worked the fixes and recommendation

2023-03-16 09:28 UTC, Anush008 commented on pages/[filterName]/insights/index.tsx
> -    getUser().catch(console.error).then(() => {});
It's just an enhancement suggestion. Won't affect the outcome in anyway.

2023-03-16 10:52 UTC, bdougie approved these changes

2023-03-16 10:54 UTC, bdougie commented on pages/[filterName]/insights/index.tsx
> -    getUser().catch(console.error).then(() => {});
I'm the event of an error I assume it would point to the useeffect, but with the current setup would name getError as the originator.

2023-03-16 12:19 UTC, Anush008 commented on pages/[filterName]/insights/index.tsx
> -    getUser().catch(console.error).then(() => {});
You're right in that sense.

2023-03-16 13:20 UTC, brandonroberts approved these changes

2023-03-16 13:20 UTC, merged