updated -fix #1038 Help button covering other buttons at bottom
open-sauced/insights pull request #1044
Opened 2023-03-22 20:22 UTC by parmishh

Fixed the issue Help button covering the discord and dev buttons at bottom
Fixes #1038

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

https://user-images.githubusercontent.com/91942072/227028446-15821997-4c69-43a2-9972-4cc9aa659724.mp4

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-03-22 21:46 UTC, Deadreyo requested changes

2023-03-22 21:46 UTC, Deadreyo commented on components/organisms/Footer/footer.tsx
> +      <div className=" container mx-auto px-2 md:px-16  lg:border-t lg:py-8 lg:items-center lg:justify-between lg:gap-x-4 flex flex-col gap-y-4 lg:flex-row py-2 w-full" style="padding-bottom:4rem;">
We're using Tailwind for the styling of the project. Please use the corresponding class from Tailwind.

2023-03-22 21:47 UTC, Deadreyo commented
For PR Compliance stuff, cc @bdougie

2023-03-23 13:15 UTC, parmishh commented
Got it working on the appropriate fix.

2023-03-25 20:34 UTC, closed without merging