feat: Repo recommendations UI
open-sauced/insights pull request #1045
Opened 2023-03-23 10:12 UTC by Deadreyo

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

- Added `TooltipProvider` into `contributor-hover-card`.
- Added missing story to stacked avatar
- Added Repo Recommendation Card to the design system.

## Related Tickets & Documents

fixes #1000 
## Mobile & Desktop Screenshots/Recordings

### Repo Recommendations Card:
![firefox_DWfrYmIQko](https://user-images.githubusercontent.com/52013393/227170370-d38e97ce-f956-4083-a2bd-037d823de81c.png)
![firefox_p79RXSZ2Ak](https://user-images.githubusercontent.com/52013393/227170378-e7575c2f-5856-4127-9a47-8800476a5941.png)

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-03-23 17:12 UTC, Deadreyo commented
Currently all tab "pages" (i.e. highlight & contributions sections) in `/username` are coded directly into the `contributor-profile-tab.ts`. This can use a refractor to separate each section into its own component to have the code easier to handle and add upon. I will start this by having this recommendations tab as a separate UI component

cc @OgDev-01 @brandonroberts

2023-03-23 20:30 UTC, bdougie approved these changes

2023-03-23 21:46 UTC, OgDev-01 commented on components/molecules/RecommendedRepoCard/recommended-repo-card.tsx
> +        <div className="flex space-x-1 items-center">
use `gap` if you have flex defined

2023-03-24 15:16 UTC, OgDev-01 approved these changes
🍕

2023-03-24 15:19 UTC, brandonroberts requested changes

2023-03-24 15:19 UTC, brandonroberts commented on components/molecules/HoverCardWrapper/hover-card-wrapper.tsx
> +import { TooltipProvider } from "@radix-ui/react-tooltip";
We already have a `TooltipProvider` in the root of the app, if you need this for the Storybook story to work, wrap the component in the story itself.

2023-03-24 16:10 UTC, brandonroberts commented on components/molecules/HoverCardWrapper/hover-card-wrapper.tsx
> +import { TooltipProvider } from "@radix-ui/react-tooltip";
We can revisit this if we need to customize the behavior at a more granular level

2023-03-24 16:11 UTC, merged