feat: implement insights team feature
open-sauced/insights pull request #1080
Opened 2023-04-05 19:58 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR is still a WIP

## Related Tickets & Documents
Closes #975

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-04-07 15:28 UTC, brandonroberts commented
@OgDev-01 the `user` has been added to the insight information https://beta.api.opensauced.pizza/#/Insights%20service/findInsightPageById

2023-04-17 16:04 UTC, brandonroberts commented
@OgDev-01 there's a build failure on the deploy preview

2023-04-17 16:09 UTC, OgDev-01 commented
> @OgDev-01 there's a build failure on the deploy preview

Fixed ✅

2023-04-17 16:47 UTC, brandonroberts requested changes

2023-04-17 16:47 UTC, brandonroberts commented on lib/hooks/useInsightMembers.ts
> +const useInsightMembers = (page_id: number) => {
Let's try to keep the naming/casing for variables in the codebase consistent

```suggestion
const useInsightMembers = (insightId: number) => {
```

2023-04-17 22:20 UTC, OgDev-01 commented on components/molecules/TeamMemberRow/team-member-row.tsx
> +    if (role === "remove") {
I have disabled the select trigger when the access is owner for now..

2023-04-18 00:32 UTC, Deadreyo commented
![image](https://user-images.githubusercontent.com/52013393/232638918-f17f98f4-fe08-4140-b7b3-16a404d683ca.png)
For some reason my name is displayed as undefined.

2023-04-18 00:51 UTC, Deadreyo requested changes

2023-04-18 00:51 UTC, Deadreyo commented on components/molecules/FilterCardSelect/filter-card-select.tsx
> +                      : icons.topic.src
This needs a refractor. Could be a switch-case in the body of the function and using a variable from there, or using the `icon` prop as a key in `icons` as in `icons[icon] ? icons[icon].src : icons.topic.src`. Etc.

2023-04-18 00:51 UTC, Deadreyo commented on components/molecules/TeamMemberRow/team-member-row.tsx
> +  onUpdate: Function;
From usage I understood that `onDelete` is a function that takes 1 argument, and `onUpdate` is a function that takes 2 arguments. This should be clearly defined in the type and have a strict structure required from the calling function. `Function` is too generic.

2023-04-18 00:51 UTC, Deadreyo commented on components/molecules/TeamMembersConfig/team-members-config.tsx
> +  onUpdateMember: Function;
Same for these. Type is too generic and doesn't represent the input or output of the function.

2023-04-18 16:07 UTC, OgDev-01 commented
> ![image](https://user-images.githubusercontent.com/52013393/232638918-f17f98f4-fe08-4140-b7b3-16a404d683ca.png) For some reason my name is displayed as undefined.

@brandonroberts any idea why this would occur?

2023-04-18 16:14 UTC, brandonroberts commented
> > ![image](https://user-images.githubusercontent.com/52013393/232638918-f17f98f4-fe08-4140-b7b3-16a404d683ca.png) For some reason my name is displayed as undefined.
> 
> @brandonroberts any idea why this would occur?

The user doesn't have a `named` defined in the database

<img width="486" alt="image" src="https://user-images.githubusercontent.com/42211/232839314-57e5bb3a-fb05-4e28-a652-d69aa81dbad0.png">

We should fallback to the `login` if its not defined

2023-04-18 18:02 UTC, OgDev-01 commented
@Deadreyo can you test again to confirm the undefined issue has been handled?

2023-04-18 18:12 UTC, Deadreyo approved these changes
Yeah it is fixed now. LGTM! 🚀

2023-04-18 18:56 UTC, brandonroberts approved these changes
LGTM

2023-04-18 20:26 UTC, bdougie approved these changes
Functionally checked it out and works for me.

2023-04-18 20:59 UTC, merged