refactor: Improve select structure for accessibility and reusability
open-sauced/insights pull request #1107
Opened 2023-04-19 13:42 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR is still a WIP

## Related Tickets & Documents
Closes #756 

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-04-21 18:08 UTC, OgDev-01 commented
How do I add Gifs to this PR ?🥲🥲... took a whole lot to get this refactor done😄

2023-04-21 18:12 UTC, bdougie commented
> How do I add Gifs to this PR ?🥲🥲... took a whole lot to get this refactor done😄

@BekahHW covered this in her latest post https://dev.to/opensauced/how-to-create-a-good-pull-request-template-and-why-you-should-add-gifs-4i0l

But if you are on chrome you can add [this extension](https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep?hl=en)

2023-04-21 18:48 UTC, OgDev-01 commented
Thanks

2023-04-21 21:22 UTC, 0-vortex commented
the language selector does not have curson pointer, therefore, not hinting it is actually clickable :D

2023-04-24 14:46 UTC, brandonroberts commented on components/organisms/Contributors/contributors.tsx
> +const colorKeys = Object.keys(color);
Why was this added?

2023-04-24 14:46 UTC, brandonroberts commented on components/organisms/UserSettingsPage/user-settings-page.tsx
> +import { RiArrowDownSLine, RiArrowUpSLine } from "react-icons/ri";
nit: move to top with other third-party imports

2023-04-24 22:30 UTC, OgDev-01 commented on components/organisms/Contributors/contributors.tsx
> +const colorKeys = Object.keys(color);
Nice catch!... My mistake...

2023-04-25 13:07 UTC, Deadreyo requested changes
Limit Select story malfunctions in the design system. If you try to select an option, it won't work as `selected` state in limit story component becomes `NaN`, due to trying to convert a string of letters into a number. You may need to re-consider the type of values going in and if you want the `value` of options to be numbers or strings (strings make more sense, even if numerical strings like "10" instead of 10).

2023-04-25 13:07 UTC, Deadreyo commented on stories/atoms/limit-select.stories.tsx
> +    { name: "fruit", value: "fruit" }
This doesn't work. `selected` state becomes `NaN` when selecting any of them.

2023-04-27 14:06 UTC, brandonroberts approved these changes

2023-04-27 14:07 UTC, merged