feat: add skeleton loading in the user's highlights tab
open-sauced/insights pull request #1191
Opened 2023-05-16 23:45 UTC by takanome-dev

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR adds a skeleton loading when the user's highlights are loading 
## Related Tickets & Documents

Fixes #986 
## Mobile & Desktop Screenshots/Recordings

Before
![before](https://user-images.githubusercontent.com/52013393/224122875-c2beda0f-b75a-4be3-878c-49d20b5924b7.png)
After
[Screencast from 05-16-2023 11:35:49 PM.webm](https://github.com/open-sauced/insights/assets/79809121/f37fc1ad-8067-439c-99ac-59e3568a45b8)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

<img src="https://media0.giphy.com/media/3o7btNa0RUYa5E7iiQ/giphy.gif"/>

2023-05-17 13:20 UTC, OgDev-01 requested changes

2023-05-17 13:20 UTC, OgDev-01 commented on components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
> +            {Array.from({ length: 3 }).map((_, index) => (
2 skeleton is enough for this... It's pointless displaying 3 when it is not visible on first load
```suggestion
            {Array.from({ length: 2 }).map((_, index) => (
```

2023-05-17 21:05 UTC, OgDev-01 approved these changes
LGTM 🍕

2023-05-18 13:55 UTC, brandonroberts approved these changes

2023-05-18 13:55 UTC, merged