feat: implement user collaboration features
open-sauced/insights pull request #1221
Opened 2023-05-24 21:09 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR is still a WIP

## Related Tickets & Documents
Closes #719

## Mobile & Desktop Screenshots/Recordings
![image](https://github.com/open-sauced/insights/assets/62995161/6ce7ce12-6ae9-4389-bd52-6580c2de52d3)

![image](https://github.com/open-sauced/insights/assets/62995161/87345225-552f-430d-848d-80b3a993eea9)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-05-25 00:15 UTC, bdougie commented
@brandonroberts any chance we can implement feature flagging for this feature? I really think the UI is ready for prime time, but it would be nice to show the feature behind the scenes. 

Perhaps we can make this for paid users only for now.

2023-05-26 13:54 UTC, brandonroberts commented
@bdougie yes, we can use the same logic for determining access to reports to restrict seeing this. We can land this and follow-up with the role check.

2023-05-30 15:39 UTC, brandonroberts requested changes

2023-05-30 15:39 UTC, brandonroberts commented on components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
> -import React, { useState, useEffect } from "react";
Organize the imports while we're in here

2023-05-30 15:39 UTC, brandonroberts commented on components/molecules/ContributorProfileHeader/contributor-profile-header.tsx
> +  const handleTextAreaInputChange = (e: ChangeEvent<HTMLTextAreaElement>) => {
We've done in this in a couple of places now. We should make this a reusable component.

2023-05-30 15:39 UTC, brandonroberts commented on components/organisms/CollaborationRequestWrapper/collaboration-requests-wrapper.tsx
> +  console.log(data);
```suggestion

```

2023-05-30 15:39 UTC, brandonroberts commented on components/organisms/CollaborationRequestWrapper/collaboration-requests-wrapper.tsx
> +        data
Create a new array if you're going to sort in place
```suggestion
        data.slice()
```

2023-05-30 15:39 UTC, brandonroberts commented on lib/hooks/useSupabaseAuth.ts
> +  const user = useStore((state) => state.user);
Did you make any changes to this file other than formatting?

2023-05-30 19:53 UTC, OgDev-01 commented on lib/hooks/useSupabaseAuth.ts
> +        options: data.options ?? {
Yeah I added users passed in option here

2023-05-31 17:28 UTC, bdougie commented
Reviewing this and not seeing the dropdown anymore. 

<img width="1283" alt="Screen Shot 2023-05-31 at 12 26 56 PM" src="https://github.com/open-sauced/insights/assets/5713670/a0a0cdc6-e84b-44d2-ab6b-4c28af308b90">

2023-05-31 19:15 UTC, OgDev-01 commented
> Reviewing this and not seeing the dropdown anymore.
> 
> <img alt="Screen Shot 2023-05-31 at 12 26 56 PM" width="1283" src="https://user-images.githubusercontent.com/5713670/242357914-a0a0cdc6-e84b-44d2-ab6b-4c28af308b90.png">

Should the dropdown also be used in the desktop view? I was thinking we use it on mobile alone.

2023-05-31 19:56 UTC, bdougie commented
We need it on desktop. 3 buttons is a bit much. We will ultimately need a better design eventually, but the dropdown works.

2023-06-05 17:49 UTC, bdougie requested changes
Per slack, we need to add a "paid user" feature flag for the collaboration button. This will allow us to test the feature and iterate.

2023-06-06 14:27 UTC, brandonroberts approved these changes
LGTM

2023-06-07 15:01 UTC, merged