feat: implement featured highlights list
open-sauced/insights pull request #1337
Opened 2023-07-07 14:49 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR implements a featured highlights list, adding a new feature to the project. The list will display important highlights or updates, making it easier for users to stay informed. This addition enhances the user experience and improves the overall functionality of the project.

_Generated using [OpenSauced](https://opensauced.ai/)._

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings
![image](https://github.com/open-sauced/insights/assets/62995161/4ba6769e-1e38-4694-9553-90e71eeca7f9)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

<img src="https://media0.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

2023-07-07 18:03 UTC, brandonroberts requested changes

2023-07-07 18:03 UTC, brandonroberts commented on pages/feed/index.tsx
> +  const { data: FeaturedHighlights } = useFetchFeaturedHighlights();
nit: camel case variables

```suggestion
  const { data: featuredHighlights } = useFetchFeaturedHighlights();
```

2023-07-07 18:03 UTC, brandonroberts commented on pages/feed/index.tsx
> +  const panelFormattedFeaturedHighlights = FeaturedHighlights?.map(({ id, title }) => ({
The mapping isn't need here if you use `DbHighlight[]` as the type

2023-07-07 18:03 UTC, brandonroberts commented on components/molecules/FeaturedHighlightsPanel/featured-highlights-panel.tsx
> +  highlights: { id: string; title: string }[];
```suggestion
  highlights: DbHighlight[];
```

2023-07-10 13:57 UTC, NsdHSO commented on stories/molecules/featured-highlights-panel.stories.tsx
> +    name: "OAuth, never missing a chance to surprise! 🍕",
Just a little fun 👍 💯 
```suggestion
    name:'A Pizza Surprise: Unleashing the Power of OAuth! 🍕🔥',
```

2023-07-10 18:25 UTC, brandonroberts commented
@OgDev-01 is there an associated issue/design for this?

2023-07-10 18:31 UTC, OgDev-01 commented
> @OgDev-01 is there an associated issue/design for this?

No we have none

2023-07-10 23:45 UTC, bdougie commented
> > @OgDev-01 is there an associated issue/design for this?
> 
> No we have none

Link the tracking issue? Just don't prefix "close" or "fixes"

2023-07-10 23:47 UTC, bdougie commented
I'd expect the "featured" highlight be orange without hover. 

![Screen Shot 2023-07-10 at 4 45 52 PM](https://github.com/open-sauced/insights/assets/5713670/918b273f-d701-4c3d-a88e-1e2ed352d651)

![Rewatch GIF Recording - 2023-07-10 at 4 47 13 PM](https://github.com/open-sauced/insights/assets/5713670/8bfed3a5-0e41-42d3-884e-b6ae2e8999f7)

Is this the correct intepretation @isabensusan?

2023-07-11 13:20 UTC, bdougie approved these changes

2023-07-11 13:48 UTC, brandonroberts approved these changes

2023-07-11 13:48 UTC, merged