Fix: Issue #1374 All suggestions are being displayed with scroll area
open-sauced/insights pull request #1380
Opened 2023-07-17 14:02 UTC by aryanas159

## Description

fixes #1374 
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-07-17 15:15 UTC, babblebey commented
@aryanas159 

Please add a Screencast (video) to this PR that demos your implementation to aid review.

2023-07-17 15:34 UTC, aryanas159 commented
@babblebey I have added the screencast.

2023-07-17 19:27 UTC, OgDev-01 approved these changes
Thanks for the fix @aryanas159 🍕 LGTM

2023-07-17 21:46 UTC, babblebey commented on components/atoms/Search/search.tsx
> +            <ScrollViewport className="max-h-60 w-full">
Remove the usage of `ScrollViewport`, use only the `ScrollArea` with a fixed height

```javascript
<ScrollArea type="auto" className="h-60">
  ...
</ScrollArea>
```
Using the `ScrollViewport` assumes you want extra customization to the T! but you don't have to.

2023-07-17 21:48 UTC, babblebey requested changes
There's another instance of suggestion counts that you have to fix:

https://github.com/open-sauced/insights/blob/beta/components/molecules/TableHeader/table-header.tsx#L67

Remove the line

```javascript
if (suggestions.length > 5) suggestions.length = 5;
```

2023-07-18 04:22 UTC, aryanas159 commented
@babblebey  Thanks for the suggestion, I was confused why I couldn't see the scrollbar. I have made the required changes.

https://github.com/open-sauced/insights/assets/114330931/2896ae0c-adc8-4ba5-9b20-87890cdd33e6

2023-07-18 04:25 UTC, bdougie approved these changes
This is a small improvement, but I would like to not the overall suggestions experience needs better data fetching and a deeper look at the UX. I expect that to happen here on the PR, but would love to discuss a better UI in an issue.

2023-07-18 05:03 UTC, merged