refactor!:  merge auth session into use session hook
open-sauced/insights pull request #1391
Opened 2023-07-19 01:50 UTC by babblebey

## Description

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-07-20 15:08 UTC, brandonroberts requested changes

2023-07-20 20:34 UTC, babblebey commented on lib/hooks/authSession.ts
> +/**
Deleted 🍕

2023-07-21 14:54 UTC, brandonroberts commented
@babblebey maybe I miscommunicated the intent here. There should only be the `useSession` hook. `authSession` should not be exported publicly. The hook should make the request where needed to initiate the session, and return the properties from the `store` to be consumed.

2023-07-21 19:28 UTC, babblebey commented
Well noted @brandonroberts 

I had few ideas to approach this in mind but here's what I settled for...

### Return a local `session` state value from the `useSession` hook in place of the `authSession`

This approach means that we'll keep/manage a local state `session` within the `useSession` hook, this `session` state value will be set on receipt of response from the `/auth/session` endpoint and then it is returned alongside the `store` managed properties (i.e. `onboarded`, `waitlisted` & `hasReports`)

```javascript
const useSession = (getSession = false) => {
  //...
  const [session, setSession] = useState(); // <- Initialising State 🍕

  useEffect(() => {
    (async () => {
      if (sessionToken && getSession) {
        const data = await loadSession();
        setSession(data); // <- Setting the State 🍕
        setStoreData(...);
      }
    })();
  }, [sessionToken]);

  return { 
    onboarded, 
    waitlisted, 
    hasReports, 
    session // <- Returned State 🍕
  };
};
```
With this approach, It means we 

- can re-fetch session from the `/auth/session` endpoint and destructure its response as `session` state value every time we call `useSession` with the `getSession` argument set to `true` without an Initial `value` retrieved from anywhere or newly set value saved anywhere outside the `useSession` hook.

```javascript
const { session } = useSession(true)
```
- retain the the ability to really not get any `session` data when `getSession` is kept at default `false`, and we are still able to retrieve the `store` saved properties (i.e. `onboarded`, `waitlisted` & `hasReports`), these values are already initialised in the `_app.tsx` component.

- simply use the destructured `session` state value from `useSession(true)` in any component we wish to integrate it. 
_Usage in `AuthSection` component_
```javascript
// components\molecules\AuthSection\auth-section.tsx

const { onboarded, session } = useSession(true);

useEffect(() => {
  const getUser = async () => {
    if (session && !userInfo) {
      setUserInfo(session);
    }
  };

  getUser();
}, [userInfo]);
```

Like so 🍕

2023-07-21 20:28 UTC, babblebey commented
👀

2023-07-25 14:19 UTC, OgDev-01 approved these changes
Looks good code wise..

2023-07-25 14:57 UTC, brandonroberts commented
@babblebey changes look good thanks. After the merge conflicts are resolved, its good to go

2023-07-25 19:47 UTC, babblebey commented
Phew 🍕

2023-07-25 20:43 UTC, merged