fix: tab inconsistency issue in user profile
open-sauced/insights pull request #1403
Opened 2023-07-21 20:27 UTC by OgDev-01

## Description
This PR fixes the issue with tab inconsistency on the user profile page

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #1402

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/insights/assets/62995161/65e72666-5731-409a-af03-53ccfbbabc98

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

<img src="https://media2.giphy.com/media/3o6Zt4RZxXV6WcUlZC/giphy.gif"/>

2023-07-21 22:20 UTC, brandonroberts approved these changes

2023-07-21 23:11 UTC, brandonroberts requested changes

2023-07-21 23:11 UTC, brandonroberts commented on components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
> +        setCurrentPathname("contributions");
Won't this create a rendering loop?

2023-07-24 18:44 UTC, OgDev-01 commented
> @OgDev-01 When I visit my profile that has highlights, I'm redirected to `contributions`
> 
> https://deploy-preview-1403--oss-insights.netlify.app/user/brandonroberts/highlights

This was happening because I didn’t update the `useEffect` dependency array with the appropriate dependencies. But i have done that now. I also made the `hasHighlight` state true by default.

2023-07-24 19:08 UTC, merged