1176 new contributor highlight card
open-sauced/insights pull request #1443
Opened 2023-07-27 14:06 UTC by OgDev-01

## Description
This PR updates the contributor's highlight card UI to now support highlights for 

This PR adds highlights for
 - Pull requests
 - Issues 
 - Blogs to the contributor's highlight card UI.

For the time being, failing to provide a type will result in a Pull request. 

This PR  also includes a story for the contributor's highlights card.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Closes #1176 

## Mobile & Desktop Screenshots/Recordings

### default
![Screenshot 2023-07-27 at 14 56 52](https://github.com/open-sauced/insights/assets/62995161/c2be271d-9a08-4902-8a18-7ec0ef5c0a1d)

### Issue
![Screenshot 2023-07-27 at 14 58 12](https://github.com/open-sauced/insights/assets/62995161/69fef0f6-eb4b-490a-bed9-d0c9b85572ed)

### Blog
![Screenshot 2023-07-27 at 14 58 49](https://github.com/open-sauced/insights/assets/62995161/20c0412a-c6eb-4d10-bab7-6bbcaa732e0a)

### New looks in feeds
![Screenshot 2023-07-27 at 14 59 33](https://github.com/open-sauced/insights/assets/62995161/a5576b16-e414-440e-beab-defca13fa918)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?
<img src="https://media1.giphy.com/media/3oEjI5VtIhHvK37WYo/giphy.gif"/>

2023-07-27 15:54 UTC, jpmcb reviewed
I'm abit confused on this change: should I be able to add issues or blog posts when creating a highlight?

When I an issue URL, it fails since it's not a valid PR link:

![Screenshot 2023-07-27 at 9 48 43 AM](https://github.com/open-sauced/insights/assets/23109390/80cb6a14-73b7-49ed-9d42-c0ffe74f549b)

This is also abit confusing from a user experience standpoint since the copy in the URL field is: "Paste your PR URL and get it auto-summarized!" Are PRs only accepted? Is that field only for auto-summarizing PRs?

2023-07-27 16:55 UTC, bdougie commented
in consistency with titles and without. Would love some spacing when there is a title. 

## without title
![Screen Shot 2023-07-27 at 9 53 55 AM](https://github.com/open-sauced/insights/assets/5713670/8225ed91-8aca-499b-917c-00e946b4ad80)

## with title
![Screen Shot 2023-07-27 at 9 53 51 AM](https://github.com/open-sauced/insights/assets/5713670/93e311d9-0477-4642-9ed7-5122d3a0df24)

2023-07-27 18:00 UTC, brandonroberts requested changes

2023-07-28 15:26 UTC, NsdHSO commented on components/molecules/ContributorHighlight/contributor-highlight-card.tsx
> +                <DropdownMenuTrigger className=" py-2 px-2 rounded-full data-[state=open]:bg-light-slate-7">
```suggestion
                <DropdownMenuTrigger className="py-2 px-2 rounded-full data-[state=open]:bg-light-slate-7">
```

2023-07-31 13:36 UTC, brandonroberts approved these changes

2023-07-31 14:52 UTC, babblebey reviewed
🍕

2023-07-31 17:03 UTC, merged