feat: add X button to clear search bar
open-sauced/insights pull request #659
Opened 2022-12-14 20:05 UTC by Deadreyo

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

Adds an "X" button that clears the search bar.
## Related Tickets & Documents

closes #345
## Mobile & Desktop Screenshots/Recordings

![image](https://user-images.githubusercontent.com/52013393/207702950-d196f623-7fd5-45bd-9f69-5b002b5558bb.png)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2022-12-14 20:22 UTC, brandonroberts requested changes

2022-12-14 20:22 UTC, brandonroberts commented on components/atoms/Search/search.tsx
> +    setSearch("");
Call the provided `onSearch` function so it triggers an update for the parent component also

```suggestion
    setSearch("");
    onSearch?.("");
```

2022-12-14 20:22 UTC, brandonroberts commented on components/atoms/Search/search.tsx
> +      { search && <GrClose className="text-light-slate-9" fontSize={16} onClick={emptySearch}/> }
nit: change click handler to `handleEmpty`

```suggestion
      { search && <GrClose className="text-light-slate-9" fontSize={16} onClick={emptySearch}/> }
```

2022-12-14 20:47 UTC, brandonroberts approved these changes
LGTM

2022-12-14 21:24 UTC, bdougie approved these changes

2022-12-14 21:37 UTC, bdougie commented
The deploy previews were blocked because this was a fork. You can open PRs locally in the repo @Deadreyo

2022-12-15 04:10 UTC, SunGoldTech approved these changes
LGTM

2022-12-15 14:11 UTC, merged