696 pr details row
open-sauced/insights pull request #706
Opened 2022-12-22 00:59 UTC by SunGoldTech

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR: 

- Updates the contributors profile page to include PRs related data

## Related Tickets & Documents
Fixes #696

## Mobile & Desktop Screenshots/Recordings

![image](https://user-images.githubusercontent.com/62995161/209031868-12678750-ddf4-4348-89c6-54941b9249e6.png)

### Mobile
![image](https://user-images.githubusercontent.com/62995161/209031949-35f914af-e115-474c-a272-ba8c7a83fede.png)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2022-12-22 13:31 UTC, bdougie commented
@SunGoldTech, looking at the OP mock and I think we should remove icons and percents altogether. They are not adding value. 

Please update the exact copy. 
- PRs Opened
- PR Velocity
- Contributed Repos 

PRs reviewed are not possible right now. 

<img width="685" alt="Screen Shot 2022-12-22 at 5 30 28 AM" src="https://user-images.githubusercontent.com/5713670/209144818-35037e5c-0511-4be4-acf4-9a993ef333be.png">

2022-12-22 14:02 UTC, SunGoldTech commented
> PRs reviewed are not possible right now.

The data received from the API call for the `useSingleContributor` hook reflects a `recent_pr_reviews` field in the return object...

### Question:

- Is the `recent_pr_reviews` field not meant for the Prs Reviewed path?

cc: @bdougie

2022-12-22 14:25 UTC, brandonroberts commented
The `recent_pr_reviews` is assigned reviews, not completed reviews. We can decide whether that's useful to show or not

2022-12-22 14:41 UTC, 0-vortex requested changes
Some minor changes needed, but LGTM! 👍

2022-12-22 14:41 UTC, 0-vortex commented on components/molecules/CardRepoList/card-repo-list.tsx
> +              <div key={`${index * Math.random()}`}>
don't assign random keys please

2022-12-22 14:41 UTC, 0-vortex commented on components/organisms/ContributorProfilePage/contributor-profile-page.tsx
> +              <div className="">
this looks like a typo 🍕

2022-12-22 14:41 UTC, 0-vortex commented on pages/user/[username].tsx
> +  console.log(contributor);
remove this as well please

2023-01-04 16:52 UTC, brandonroberts commented
@OgDev-01 this one needs merge conflicts to be resolved also

2023-01-05 19:02 UTC, 0-vortex approved these changes

2023-01-05 20:47 UTC, merged