feat: Add `PullRequestSocialCard` component to design system
open-sauced/insights pull request #774
Opened 2023-01-13 09:28 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR is still a work in progress

## Related Tickets & Documents
Fixes #716 

## Mobile & Desktop Screenshots/Recordings
### Current data precent on card
<img width="498" alt="image" src="https://user-images.githubusercontent.com/62995161/212285435-c880f20b-9c02-4d63-9d33-ef1c99667b36.png">

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-01-23 16:20 UTC, brandonroberts commented
@OgDev-01 there's a build failure and I'm unable to see the design system preview

2023-01-24 14:00 UTC, brandonroberts requested changes

2023-01-24 14:00 UTC, brandonroberts commented on components/molecules/PullRequestSocialCard/pull-request-social-card.tsx
> +        <Avatar alt="" avatarURL={avatar} initials="" size="sm" className="" />
Remove empty className

```suggestion
        <Avatar alt="" avatarURL={avatar} initials="" size="sm"  />
```

2023-01-24 15:05 UTC, OgDev-01 commented on components/molecules/PullRequestSocialCard/pull-request-social-card.tsx
> +    <div className="w-[26.375rem] cursor-pointer border rounded-xl px-5 py-4">
That's the pixels equivalent in rem from the design, and tailwind has no size value for that.

2023-01-24 15:38 UTC, brandonroberts commented on components/molecules/PullRequestSocialCard/pull-request-social-card.tsx
> +          {linesAdded && (
This should still display if the `linesAdded` is 0

2023-01-24 15:39 UTC, brandonroberts requested changes

2023-01-24 15:39 UTC, brandonroberts commented on components/molecules/PullRequestSocialCard/pull-request-social-card.tsx
> +          {linesRemoved && (
This should still display if the `linesRemoved` is 0.

2023-01-24 16:09 UTC, brandonroberts approved these changes

2023-01-24 16:38 UTC, brandonroberts commented on components/molecules/PullRequestSocialCard/pull-request-social-card.tsx
> +          <span className="text-light-slate-10 ">{prTicketId}</span> {prTitle}
Might need to truncate this, but can be for a follow-up

2023-01-24 16:38 UTC, merged