feat: implement profile settings feature
open-sauced/insights pull request #808
Opened 2023-01-27 18:52 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR is still a work in progress

## Related Tickets & Documents
Fixes #794 

## Mobile & Desktop Screenshots/Recordings

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/62995161/215170549-1e8d6eb8-28aa-459e-ab48-e973b6060a4f.png">

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-01-28 17:15 UTC, bdougie requested changes
A few copy changes. Also mentioned this a few times, but we need UTC in the timezone list. 

Starts from UTC-12 and goes to UTC+14. UTC with no juncture should show in this list. 

<img width="476" alt="Screen Shot 2023-01-28 at 9 14 13 AM" src="https://user-images.githubusercontent.com/5713670/215279857-6b4ed733-f5c8-4163-9a31-0e3e81718c57.png">

2023-01-28 17:15 UTC, bdougie commented on components/organisms/UserSettingsPage/user-settings-page.tsx
> +              <Checkbox disabled value={"true"} title="profile email" label="Display current local time" />
```suggestion
              <Checkbox disabled value={"true"} title="profile email" label="Display current local time on profile" />
```

2023-01-28 17:15 UTC, bdougie commented on components/organisms/UserSettingsPage/user-settings-page.tsx
>                <Checkbox value={"true"} title="profile email" label="Display Email On Profile" />
```suggestion
              <Checkbox value={"false"} title="profile email" label="Display email on profile" />
```

- This should be false by default
- Change to sentence case

2023-01-28 17:15 UTC, bdougie commented on components/organisms/UserSettingsPage/user-settings-page.tsx
>                <Checkbox value={"true"} title="collaboration requests" label="Receive collaboration requests" />
```suggestion
              <Checkbox value={"false"} title="collaboration requests" label="Receive collaboration requests" />
```
False by default

2023-01-29 00:12 UTC, getaheaddev commented
Instead of using the github profile photo use the SVG. It'll prevent it from be over used.

![person-icon f2841f1e](https://user-images.githubusercontent.com/122071536/215296937-56132bc2-370e-4470-90b5-858708e82e73.svg)

![Screenshot 2023-01-28 at 5 11 52 PM](https://user-images.githubusercontent.com/122071536/215296969-2067bd2d-ee6c-4454-9932-f5693e64ed77.png)

![Screenshot 2023-01-28 at 5 12 00 PM](https://user-images.githubusercontent.com/122071536/215296971-b3b93446-d08d-4f22-89d0-666195feeea1.png)

2023-01-30 18:03 UTC, bdougie requested changes
Remind me Sunday, is getting an error expected? 

- can add the 🚫 cursor on the disabled fields?
- Updating my timezone is not working. Pictured below.
- Can't click any checkbox?
- Need to remove avatar and use the person svg

Also @brandonroberts are the elements like bio, url, and twitter username available in the api?

<img width="589" alt="Screen Shot 2023-01-30 at 9 57 22 AM" src="https://user-images.githubusercontent.com/5713670/215556958-5fbff277-3e7f-4b1c-9151-4020d482c496.png">

2023-01-30 18:10 UTC, bdougie commented
> * Updating my timezone is not working. Pictured below.

<img width="513" alt="Screen Shot 2023-01-30 at 10 09 53 AM" src="https://user-images.githubusercontent.com/5713670/215560279-40ad9f49-3bb1-4dfa-ae4b-bd1e266cf58f.png">

2023-01-30 18:26 UTC, brandonroberts commented
@bdougie yes those are available in the authenticated session and the public user profile data

2023-01-30 18:28 UTC, bdougie commented
> @bdougie yes those are available in the authenticated session and the public user profile data

Ok @OgDev-01 if these are available can we add these in the UI, or come up with a plan to update them shortly after. We got a slow start on this feature and I'd love to ship what is usable as soon as possible.

2023-01-30 18:34 UTC, OgDev-01 commented
> > @bdougie yes those are available in the authenticated session and the public user profile data
> 
> Ok @OgDev-01 if these are available can we add these in the UI, or come up with a plan to update them shortly after. We got a slow start on this feature and I'd love to ship what is usable as soon as possible.

What is the URL field intended for?

2023-01-30 19:05 UTC, brandonroberts commented
@OgDev-01 the `url` field could be there primary website or some other URL they have on their GitHub profile data

2023-01-30 19:09 UTC, bdougie commented
> @OgDev-01 the `url` field could be their primary website or some other URL they have on their GitHub profile data

Mine is currently https://b.dougie.dev

I'd also recommend we updated th placeholder copy to be ContributorInfo that is already display on the profile pages on your other PR.

2023-01-31 00:34 UTC, OgDev-01 commented on lib/hooks/update-user.ts
> +const UpdateUser = async ({ token, data, params }: useUpdateUserProps) => {
since it's in the hooks folder, I should as well add the use prefix to it, right? to stay in uniform

2023-01-31 01:00 UTC, OgDev-01 commented on lib/hooks/useAuthSession.ts
> +  const { data, error } = useSWR<UserResponse, Error>("auth/session", publicApiFetcher as Fetcher<UserResponse, Error>);
how can I prevent this from caching?

2023-01-31 01:45 UTC, bdougie requested changes

2023-01-31 01:45 UTC, bdougie commented on components/organisms/UserSettingsPage/user-settings-page.tsx
> +              value={`@${(userInfo && userInfo.twitter_username) || "open-sauced-user"}`}
```suggestion
              value={`@${(userInfo && userInfo.twitter_username) || "saucedopen"}`}
```

2023-01-31 01:45 UTC, bdougie commented on components/organisms/UserSettingsPage/user-settings-page.tsx
> +              value={userInfo?.location || "Romania"}
```suggestion
              value={userInfo?.location || "Canada"}
```
I would love to like to leverage a country with a higher chance of usage.

2023-01-31 01:45 UTC, bdougie commented on components/organisms/UserSettingsPage/user-settings-page.tsx
> +              value={userInfo?.company || "open sauced"}
```suggestion
              value={userInfo?.company || "OpenSauced"}
```

2023-01-31 12:48 UTC, bdougie commented
Just looked at this on mobile and it is all off.

![image](https://user-images.githubusercontent.com/5713670/215764048-3c941c3f-e2cc-4d1b-a7f0-8099e59c6222.png)

2023-01-31 14:26 UTC, brandonroberts commented on lib/hooks/useAuthSession.ts
> +  const { data, error } = useSWR<UserResponse, Error>("auth/session", publicApiFetcher as Fetcher<UserResponse, Error>);
Use a regular `fetch` call instead of `useSWR`

2023-01-31 14:42 UTC, brandonroberts commented on components/organisms/UserSettingsPage/user-settings-page.tsx
>    const [selectedInterest, setSelectedInterest] = useState<string[]>([]);
I should have `interests` pre-selected from the data in my user profile, such as `javascript`

2023-01-31 15:13 UTC, brandonroberts commented
@OgDev-01 there is an endpoint available for updating the `Email Interests` in the API now also. 

The endpoint is a `PATCH` request for `/auth/profile/email`
The two fields are `display_email` and `receive_collaboration`.

2023-01-31 15:42 UTC, OgDev-01 commented
> @OgDev-01 there is an endpoint available for updating the `Email Interests` in the API now also.
> 
> The endpoint is a `PATCH` request for `/auth/profile/email` The two fields are `display_email` and `receive_collaboration`.

Going through the API docs now, and it shows `email` as the required field in the body of the request, should this be ignored?

2023-01-31 15:48 UTC, brandonroberts commented
@OgDev-01 yes, that's just a mistake in the swagger docs. I'll update that

2023-01-31 18:09 UTC, bdougie approved these changes
Looks good. Thanks for keeping this on track.

2023-01-31 18:16 UTC, OgDev-01 commented on lib/hooks/useAuthSession.ts
> +  const { data, error } = useSWR<UserResponse, Error>("auth/session", publicApiFetcher as Fetcher<UserResponse, Error>);
Ok

2023-01-31 18:18 UTC, 0-vortex requested changes
Some stray `console.log`s and branch not updated to latest beta but LGTM otherwise! 👍

2023-01-31 18:30 UTC, brandonroberts approved these changes
Need to remove the cached auth/session hook, but LGTM

2023-01-31 18:33 UTC, brandonroberts commented
@OgDev-01 the `Update Profile` button is disabled initially until you update the `email` field. It should be enabled by default if the email is valid.

2023-01-31 20:16 UTC, brandonroberts approved these changes
LGTM

2023-01-31 20:17 UTC, brandonroberts commented
@OgDev-01 just needs the fix on the build failure and we're good to merge

2023-02-01 14:49 UTC, merged