fix:truncate text on mobile (#805) & move dropdown (#806)
open-sauced/insights pull request #863
Opened 2023-02-10 19:33 UTC by Themesses

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
PR fixes two issues on mobile resolution:

#805 
Filter button breaks out of the container on long repo names. To fix this, the text was truncated with an ellipsis. A further enhancement is possible by removing 'filtered by' or shortening it simply to 'by', if necessary. 

#806 
The drop-down was moved to the left on mobile, to prevent the content from being cut off. 

## Related Tickets & Documents
Fixes #805 
Fixes #806

## Mobile & Desktop Screenshots/Recordings
Before:
https://user-images.githubusercontent.com/43274289/218179334-06e39998-4c53-4176-a917-90f7875807a3.mov

After:

https://user-images.githubusercontent.com/43274289/218180415-6457eb0b-0d69-4135-a338-19aab371e86b.mov

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-02-10 22:05 UTC, Themesses commented
> Looks great @Themesses 👍
> 
> There are some formatting issues that fail the build. Try running `npm run format` and then `npm run build` to check if it's good (no error)
> 

@TAKANOME-DEV if you want to take a look, the build seems to be up. And thanks for the tip!

2023-02-11 08:49 UTC, 0-vortex requested changes
LGTM except the `!important` classes, removing those should do the trick! 👍

2023-02-11 08:49 UTC, 0-vortex commented on components/molecules/SuperlativeSelector/superlative-selector.tsx
> +    <div className="!overflow-hidden !text-ellipsis !whitespace-nowrap  md:relative md:!whitespace-normal md:!overflow-visible md:!text-base max-w-max" ref={ref}>
please remove the '!' (important) classes, we cannot manage them :<

2023-02-11 09:40 UTC, Themesses commented
> LGTM except the `!important` classes, removing those should do the trick! 👍

@0-vortex love the feedback and thanks! Classes removed.

2023-02-11 15:09 UTC, bdougie approved these changes
🚀

2023-02-11 15:17 UTC, 0-vortex commented
> > LGTM except the `!important` classes, removing those should do the trick! 👍
> 
> @0-vortex love the feedback and thanks! Classes removed.

Awesome, can you also remove the commented div? If @bdougie 👍 we can merge it over the weekend too! 🍕

2023-02-11 23:45 UTC, Themesses commented
@0-vortex got rid of the commented divs as well as some empty ones that weren't really doing anything.

2023-02-12 12:08 UTC, TAKANOME-DEV commented
The deploy preview looks fine on Firefox but not on Brave and Chrome for me :thinking: 
Does anyone noticed the same or it's just mine? 
- Firefox
![firefox](https://user-images.githubusercontent.com/79809121/218309979-e2b340be-9a18-4f41-bba8-3ab58e4b7f7b.png)
- Brave
![brave](https://user-images.githubusercontent.com/79809121/218309994-f963b9a5-03d3-46c8-a255-90db81ff0039.png)
- Chrome
![chrome](https://user-images.githubusercontent.com/79809121/218310009-00d6ff3b-62a6-4322-9e60-bfa02ec4b061.png)
cc @Themesses

2023-02-12 12:40 UTC, Themesses commented
> The deploy preview looks fine on Firefox but not on Brave and Chrome for me 🤔 Does anyone noticed the same or it's just mine?

Great catch @TAKANOME-DEV .On a Mac, Brave and Firefox seem to work as intended for me. I wonder if it's just simply the medium resolution. I made an assumption that you wouldn't need to truncate on anything other than mobile. Can you give me the screen width where that happens

2023-02-13 12:51 UTC, Themesses commented
@TAKANOME-DEV  Here's the new behavior, let me know if that works: 


https://user-images.githubusercontent.com/43274289/218462444-54129e67-7492-46f7-accf-85b7ddd82fd8.mov

2023-02-13 15:30 UTC, brandonroberts approved these changes

2023-02-13 15:30 UTC, brandonroberts commented on components/molecules/SuperlativeSelector/superlative-selector.tsx
> +    console.log("current ref", ref.current?.getBoundingClientRect());
nit: remove console.log

2023-02-13 18:43 UTC, merged

2023-02-13 18:43 UTC, brandonroberts commented
Thanks @Themesses!