fix: input reset bug
open-sauced/insights pull request #869
Opened 2023-02-12 12:49 UTC by TAKANOME-DEV

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

This PR fixes the input reset bug by clearing the input state when the clear (`x`) button is clicked
## Related Tickets & Documents

Fixes #858
## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-02-13 14:31 UTC, Deadreyo commented
While this solution is correct, it adds an overhead of assigning a new prop `onReset` each place the component is needed. I wonder if you could remove that overhead by having the reset functionality be an internal part of the component, maybe by manually triggering an event with the value being an empty string?

2023-02-13 21:42 UTC, TAKANOME-DEV commented
> While this solution is correct, it adds an overhead of assigning a new prop onReset each place the component is needed.
>
I agree.
> I wonder if you could remove that overhead by having the reset functionality be an internal part of the component, maybe by manually triggering an event with the value being an empty string?
>
Hum, would it be different to pass a handler as props to clear the input instead of using `onReset` handler?

Using `useRef` instead of `useState` will solve the problem but the close button won't show up. Do you think I should go that route?

2023-02-14 20:40 UTC, Deadreyo commented
> Hum, would it be different to pass a handler as props to clear the input instead of using `onReset` handler?

Still requiring a new prop, didn't change anything.
Another way to go about this is to change the type of the `onchange` prop to be a function that takes string as input, and have a handler function for the state passed into it. Then from inside you can control what the state becomes.

2023-02-15 13:04 UTC, TAKANOME-DEV commented on components/atoms/TextInput/text-input.tsx
> +      onReset();
Yeah, that's right :+1:

2023-02-15 13:05 UTC, TAKANOME-DEV commented on components/atoms/TextInput/text-input.tsx
> +      onReset();
```suggestion
      onReset?.();
```

2023-02-15 15:54 UTC, brandonroberts requested changes
Merge conflicts should be resolved also

2023-02-15 15:54 UTC, brandonroberts commented on components/atoms/TextInput/text-input.tsx
> +    console.log({fieldRef});
nit: console log

```suggestion
```

2023-02-15 22:46 UTC, TAKANOME-DEV commented
> Another way to go about this is to change the type of the `onchange` prop to be a function that takes string as input, and have a handler function for the state passed into it. Then from inside you can control what the state becomes.
>
Can you provide an example?

2023-02-16 14:59 UTC, brandonroberts approved these changes

2023-02-16 16:49 UTC, Deadreyo commented
> > Another way to go about this is to change the type of the `onchange` prop to be a function that takes string as input, and have a handler function for the state passed into it. Then from inside you can control what the state becomes.
> 
> Can you provide an example?

A simple example consisting of "component1" and "component2"
```ts
const component1 = () => {
const [state, setState] = useState("")

const handleChangeState = (value) => setState(value)

return (
 <component2 handleChange={handleChangeState} />
```
```ts
const component2 = ({ handleChangeState }) => {

const handleReset = () => handleChangeState("")
const handleChange = (e) => handleChangeState(e.target.value)
return (
<input onchange={handleChange} />
```
The difference is that the function in this example is a simple function that takes a string and changes the state, so the Reset can be done without needing another function. However the current implementation is that the function passed as prop takes an event, so can't do this. My suggestion is changing that.

2023-02-16 20:08 UTC, TAKANOME-DEV commented
Thanks for the example @Deadreyo :+1:

2023-02-16 20:53 UTC, Deadreyo approved these changes
LGTM!

2023-02-17 00:53 UTC, brandonroberts approved these changes

2023-02-17 00:54 UTC, merged