feat: add dropdown for topics in Explore
open-sauced/insights pull request #877
Opened 2023-02-15 15:03 UTC by Deadreyo

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

closes #533 
## Mobile & Desktop Screenshots/Recordings
![image](https://user-images.githubusercontent.com/52013393/219064891-5422c0b8-85e9-4e51-adc6-be45045da700.png)
![image](https://user-images.githubusercontent.com/52013393/219065276-7fd77d89-2d30-409a-95ce-9c6fe7fa2478.png)

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-02-15 19:33 UTC, bdougie requested changes
This section is meant to share totals. If that is not possible, could we delete

<img width="360" alt="Screen Shot 2023-02-15 at 2 32 29 PM" src="https://user-images.githubusercontent.com/5713670/219133744-06f18372-fa64-439c-b63a-caed5f3e1775.png">

2023-02-16 14:52 UTC, brandonroberts commented
> This section is meant to share totals PRs represented in the topic. If that is not possible, could we delete circle UI element.
> 
> <img alt="Screen Shot 2023-02-15 at 2 32 29 PM" width="360" src="https://user-images.githubusercontent.com/5713670/219133744-06f18372-fa64-439c-b63a-caed5f3e1775.png">

I think we should remove it for now

2023-02-16 14:53 UTC, brandonroberts requested changes

2023-02-16 14:53 UTC, brandonroberts commented on lib/hooks/useTopicOptions.ts
> +const useTopicOptions = () => {
By convention, this should not be prefixed with `use` as it is not a hook, but a function that returns data. It should also be moved to `lib/utils`

```suggestion
const getTopicOptions = () => {
```

2023-02-16 14:53 UTC, brandonroberts commented on components/molecules/FilterCardSelect/filter-card-select.tsx
> +    const checkIfClickedOutside = (e: any) => {
This should not be `e: any`. 

```suggestion
    const checkIfClickedOutside = (e: MouseEvent) => {
```

2023-02-16 19:40 UTC, Deadreyo commented
> This section is meant to share totals PRs represented in the topic. If that is not possible, could we delete circle UI element.
> 
> <img alt="Screen Shot 2023-02-15 at 2 32 29 PM" width="360" src="https://user-images.githubusercontent.com/5713670/219133744-06f18372-fa64-439c-b63a-caed5f3e1775.png">

deleted

2023-02-17 14:06 UTC, bdougie approved these changes

2023-02-17 16:17 UTC, brandonroberts approved these changes

2023-02-17 16:17 UTC, merged