feat: implement edit highlight
open-sauced/insights pull request #909
Opened 2023-02-24 16:23 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR is still a WIP

## Related Tickets & Documents
Fixes #886 

## Mobile & Desktop Screenshots/Recordings

![image](https://user-images.githubusercontent.com/62995161/221231563-5cd51fbd-8bfd-4499-941d-772c7d7e60cc.png)

![image](https://user-images.githubusercontent.com/62995161/221231623-dcc67d2f-8287-408d-b8b2-1e4e6f1631fc.png)

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-02-24 20:00 UTC, bdougie commented on components/molecules/ContributorHighlight/contributor-highlight-card.tsx
> +        setError("Please provide a valid github pull url");
```suggestion
        setError("Please provide a valid github pull url");
```
```suggestion
        setError("Please provide a valid github pull request url");
```

2023-02-24 20:01 UTC, bdougie requested changes
needs to be "pull request"

2023-02-24 20:01 UTC, bdougie commented on components/molecules/ContributorHighlight/contributor-highlight-card.tsx
> +      setError("Please provide a valid github pull url");
```suggestion
      setError("Please provide a valid github pull request url");
```

2023-02-24 20:59 UTC, bdougie approved these changes
Looks good. I committed some copy updates

2023-02-26 17:40 UTC, shamimbinnur commented
@OgDev-01  I am gonna replicate this [dialog.tsx](https://github.com/open-sauced/insights/blob/886-new-update-highlight/components/molecules/Dialog/dialog.tsx) on my branch and use it for the issue #853. To avoid conflict I need confirmation that this is reusable for future work and you are not gonna make any changes to the [dialog.tsx](https://github.com/open-sauced/insights/blob/886-new-update-highlight/components/molecules/Dialog/dialog.tsx) at least in this PR.

2023-02-27 01:02 UTC, merged

2023-02-27 01:02 UTC, bdougie commented
merge the PR. You can work off beta to get the components final state @shamimbinnur

2023-03-05 02:08 UTC, Charliebrickman75 commented on components/molecules/ContributorHighlight/contributor-highlight-card.tsx
> +        setError("Please provide a valid github pull url");
Did this work?