topic based on user interest
open-sauced/insights pull request #930
Opened 2023-03-01 14:42 UTC by shamimbinnur

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
I fetched the value of the user's interests from the database using `useFetchUser()`, which indicates the language they are interested in and set it as their default topic.

## Related Tickets & Documents
Fixes #929 

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-03-01 15:08 UTC, TAKANOME-DEV reviewed
@shamimbinnur if the user has multiple interests, maybe we should pick the first one. Check the screenshot below

![Screenshot from 2023-03-01 15-06-50](https://user-images.githubusercontent.com/79809121/222179837-19cd1fa2-83f7-4748-a274-9ad7b23012c9.png)

2023-03-01 15:08 UTC, TAKANOME-DEV commented on components/organisms/TopNav/top-nav.tsx
> +  const userInterests = gitHubUser?.interests || "javascript";
```suggestion
  const userInterests = gitHubUser?.interests?.[0] || "javascript";
```

2023-03-01 15:14 UTC, bdougie commented
It tries to add all topics. Should just grab the first.

![Screen Shot 2023-03-01 at 7 07 29 AM](https://user-images.githubusercontent.com/5713670/222179698-30fc979f-e05d-41b1-94e7-c6eddb2a6211.png)

2023-03-01 15:57 UTC, brandonroberts requested changes

2023-03-01 15:57 UTC, brandonroberts commented on components/organisms/TopNav/top-nav.tsx
> +            <Link className="text-sm text-light-slate-10" href={"/"+userInterest+"/dashboard/filter/recent"}>
Let's use a template literal here instead

```suggestion
            <Link className="text-sm text-light-slate-10" href={`${userInterest}/dashboard/filter/recent`}>
```

2023-03-01 16:02 UTC, TAKANOME-DEV approved these changes
LGTM :+1:

2023-03-01 16:54 UTC, bdougie approved these changes
Looks good

2023-03-01 18:36 UTC, brandonroberts approved these changes
LGTM. We'll need to hook this into the user settings being updated also, but separate from this

2023-03-01 18:37 UTC, merged

2023-03-03 15:51 UTC, shamimbinnur commented
@brandonroberts  I just noticed this [line](https://github.com/open-sauced/insights/blob/fddd634467aa16da18c6111aada1a8ed42ef248a/components/organisms/TopNav/top-nav.tsx#L30) has not been updated. Was it intentional?

2023-03-03 16:32 UTC, brandonroberts commented
@shamimbinnur it was not intentional. It got changed accidentally while resolving some merge conflicts. It should be reapplied