feat: add custom tooltip to pr list icon
open-sauced/insights pull request #962
Opened 2023-03-07 11:55 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR adds the systems custom tooltip to the pr list role icons with better description text

## Related Tickets & Documents
Fixes #955 

## Mobile & Desktop Screenshots/Recordings
### Exp
<img width="380" alt="image" src="https://user-images.githubusercontent.com/62995161/223415023-fdc99108-a28f-4128-bbd3-d8e57877146f.png">

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-03-07 14:25 UTC, brandonroberts approved these changes

2023-03-07 17:52 UTC, bdougie requested changes
Can we add tooltips to all icons

![Screen Shot 2023-03-07 at 9 50 26 AM](https://user-images.githubusercontent.com/5713670/223506741-e7a76a21-25c2-4b1a-95b6-fbc9a976ef4f.png)
- PRs merged
- First commit date

![Screen Shot 2023-03-07 at 9 49 46 AM](https://user-images.githubusercontent.com/5713670/223506909-f1f3516a-1a8c-4011-9e0a-585ba470e799.png)
- Time zone
- First commit date

2023-03-07 19:22 UTC, Deadreyo approved these changes

2023-03-08 13:17 UTC, bdougie approved these changes

2023-03-08 14:00 UTC, merged