feat: adds zendesk to the app
open-sauced/insights pull request #979
Opened 2023-03-08 21:16 UTC by bdougie

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-03-10 15:08 UTC, 0-vortex requested changes
This should go in after the footer, at the end of all the paintable content, this should be a pattern for all the static scripts like google analytics, etc, then just ship IMHO 🔥

2023-03-11 18:14 UTC, 0-vortex approved these changes
LGTM 👍  but I have a question: does this need to be disabled somehow for development and test channels like alpha and beta?

2023-03-11 18:31 UTC, bdougie commented
We could but zendesk tracks the irl the message is from. 

I think we turn it off for localhost though

2023-03-14 13:40 UTC, brandonroberts approved these changes

2023-03-14 13:41 UTC, merged